using System;
using System.Collections.Generic;

namespace ApplicationCore.Models
{
    public partial class VPkRepo
    {
        public decimal Nrepokey { get; set; }
        public bool? Bbrokerage { get; set; }
        public bool? Bcouponreinvestment { get; set; }
        public bool? Bdividend { get; set; }
        public decimal? Binternal { get; set; }
        public decimal? Bnetting { get; set; }
        public decimal? Bnocrs { get; set; }
        public bool? Bnosummit { get; set; }
        public bool? Bopenpos { get; set; }
        public bool? Bsalestrade { get; set; }
        public string Cbookcode { get; set; }
        public string Cclientcode { get; set; }
        public string Ccomment { get; set; }
        public string Ccontrcode { get; set; }
        public string Ccpclientcode { get; set; }
        public string Ccurrcode { get; set; }
        public string Cdealercode { get; set; }
        public string Cdealnumber { get; set; }
        public string Cdownside { get; set; }
        public string Copcode { get; set; }
        public string Creutersimportfile { get; set; }
        public string Csalesname { get; set; }
        public string Cticket { get; set; }
        public string Cupside { get; set; }
        public DateTime? Daudittimestamp { get; set; }
        public DateTime? Dclosedate { get; set; }
        public DateTime? Dclosedeliverydate { get; set; }
        public DateTime? Dclosepaymentdate { get; set; }
        public DateTime? Dcontrdate { get; set; }
        public DateTime? Ddateofcoupon { get; set; }
        public DateTime? Dregdate { get; set; }
        public DateTime? Dstartdate { get; set; }
        public DateTime? Dstartdeliverydate { get; set; }
        public DateTime? Dstartpaymentdate { get; set; }
        public decimal? Ilogverify { get; set; }
        public decimal? Isb { get; set; }
        public decimal? Nacckey { get; set; }
        public decimal? Ncharges { get; set; }
        public decimal? Ncomission { get; set; }
        public decimal? Ndealkey { get; set; }
        public decimal? Ndividendsum { get; set; }
        public decimal? Ndividendtax { get; set; }
        public decimal? Ndividentrate { get; set; }
        public decimal? Ndowntrigger { get; set; }
        public decimal? Nfxrate { get; set; }
        public decimal? Nhaircut { get; set; }
        public decimal? Ninternalkey { get; set; }
        public decimal? Nlogreckey { get; set; }
        public decimal? Nloguserkey { get; set; }
        public decimal? Nmarketprice { get; set; }
        public decimal? Nmarketsum { get; set; }
        public decimal? Nmarketsum2 { get; set; }
        public decimal? Noldrepotype { get; set; }
        public decimal? Nplpct { get; set; }
        public decimal? Nprice { get; set; }
        public decimal? Nprice2 { get; set; }
        public decimal? Nrateofreinvest { get; set; }
        public decimal? Nrepobase { get; set; }
        public decimal? Nreporate { get; set; }
        public decimal? Nreposum { get; set; }
        public decimal? Nreposum2 { get; set; }
        public decimal? Nsalescredit { get; set; }
        public decimal? Nsalesrate { get; set; }
        public decimal? Nsecuritykey { get; set; }
        public decimal? Nsecuritytypekey { get; set; }
        public decimal? Nsettelmenttype { get; set; }
        public decimal? Nsettlementplacekey { get; set; }
        public decimal? Nsourcekey { get; set; }
        public decimal? Nstep { get; set; }
        public decimal? Nsumkup { get; set; }
        public decimal? Nsumkup2 { get; set; }
        public decimal? Nsumnom { get; set; }
        public decimal? Nsumnom2 { get; set; }
        public decimal? Nsumofreinvest { get; set; }
        public decimal? Ntradenum { get; set; }
        public decimal? Ntradeplace { get; set; }
        public decimal? Nuptrigger { get; set; }
        public string Csb { get; set; }
        public string Csecuritytypekey { get; set; }
        public string Csettelmenttype { get; set; }
        public string Csettlementplacekey { get; set; }
        public string Ctradeplace { get; set; }
        public string Cacckey { get; set; }
        public string Cbrokagagreementfm { get; set; }
        public string Ccontrname { get; set; }
        public string Ccouponrate { get; set; }
        public string Cdealername { get; set; }
        public string Cequitykey { get; set; }
        public string Cequityticker { get; set; }
        public string Cisin { get; set; }
        public string Cisinreal { get; set; }
        public string Cissuer { get; set; }
        public string Cseccode { get; set; }
        public string Cseccomment { get; set; }
        public string Csecdesc { get; set; }
        public string Ctranshcurr { get; set; }
        public string Ctranshkey { get; set; }
        public DateTime? Dmaturitydate { get; set; }
        public decimal? Icurrweight { get; set; }
        public string Ngridid { get; set; }
        public decimal? Nsecnom { get; set; }
        public string Csecuritykey { get; set; }
        public string Ccrsstatus { get; set; }
        public string Cdiasoftstatus { get; set; }
        public string Csummitstatus { get; set; }
        public decimal? Nduration { get; set; }
        public decimal? Nequitykey { get; set; }
        public decimal? Ntranshkey { get; set; }
        public decimal? NuserkeyTmp { get; set; }
        public DateTime? DactualdateTmp { get; set; }
        public DateTime DcreatedateTmp { get; set; }
        public bool? BendflagTmp { get; set; }
        public decimal? NvernumberTmp { get; set; }
        public decimal? Ntt { get; set; }
        public decimal? Naccesscontrolfield { get; set; }
    }
}
